name: flutter_application_2
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  path_provider: ^2.0.15
  flutter_bloc: ^8.1.2
  uuid: ^3.0.7
  persian_datetime_picker: ^2.5.0
  animate_do: ^3.0.2
  awesome_dialog: ^3.0.2
  flutter_custom_clippers: ^2.1.0
  shamsi_date: ^1.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  flutter_spinkit: ^5.2.0
  flutter_screenutil: ^5.7.0


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

    
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/service/
    - assets/fonts/

  fonts:
      - family: IranSans
        fonts:
            - asset: assets/fonts/IRANSansXFaNum-Bold.ttf
            - asset: assets/fonts/IRANSansXFaNum-Regular.ttf

  
  
  
  
  
  
  
  
  
  
